name: build and deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps:
      - name: Checkout    
        uses: actions/checkout@v4.1.2
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        
      - name: Install Dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
          
  deploy:
    runs-on: ubuntu-latest 
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          # 本地.ssh文件下的私钥id_rsa，存在secrets的PRIVATE_KEY中
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
          ARGS: "-avzr --delete" 
          # 服务器域名/IP
          REMOTE_HOST: ${{ secrets.HOST }}
          # 服务器用户名
          REMOTE_USER: "wangfu"
          SOURCE: "./"
          # 目标目录
          TARGET: '/home/wangfu/wangfu_paper_web'
